In [7]:
import pandas as pd

In [8]:
df = pd.read_csv("sentiment.csv")

In [9]:
df

,textID,text,selected_text,sentiment,Time of Tweet,Age of User,Country,Population -2020,Land Area (Km),Density (P/Km)
0,cb774db0d1,"I`d have responded, if I were going","I`d have responded, if I were going",neutral,morning,0-20,Afghanistan,38928346,652860.0,60
1,549e992a42,Sooo SAD I will miss you here in San Diego!!!,Sooo SAD,negative,noon,21-30,Albania,2877797,27400.0,105
2,088c60f138,my boss is bullying me...,bullying me,negative,night,31-45,Algeria,43851044,2381740.0,18
3,9642c003ef,what interview! leave me alone,leave me alone,negative,morning,46-60,Andorra,77265,470.0,164
4,358bd9e861,"Sons of ****, why couldn`t they put them on t...","Sons of ****,",negative,noon,60-70,Angola,32866272,1246700.0,26
...,...,...,...,...,...,...,...,...,...,...
27476,4eac33d1c0,wish we could come see u on Denver husband l...,d lost,negative,night,31-45,Ghana,31072940,227540.0,137
27477,4f4c4fc327,I`ve wondered about rake to. The client has ...,", don`t force",negative,morning,46-60,Greece,10423054,128900.0,81
27478,f67aae2310,Yay good for both of you. Enjoy the break - y...,Yay good for both of you.,positive,noon,60-70,Grenada,112523,340.0,331
27479,ed167662a5,But it was worth it ****.,But it was worth it ****.,positive,night,70-100,Guatemala,17915568,107160.0,167
27480,6f7127d9d7,All this flirting going on - The ATG smiles...,All this flirting going on - The ATG smiles. Y...,neutral,morning,0-20,Guinea,13132795,246000.0,53

In [11]:
df = df[["text","sentiment"]]

In [13]:
df.dropna(inplace=True)

C:\Users\Welcome\AppData\Local\Temp\ipykernel_2772\1379821321.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(inplace=True)

In [ ]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from string import punctuation

In [18]:
tokens = []

for doc in df['text']:
    token = word_tokenize(doc, language = 'english', preserve_line = True)
    token = [i for i in token if i not in punctuation]
    tokens.append(token)

res = []
for doc in tokens:
    token = [i for i in doc if i not in stopwords.words('english')]
    res.append(token)

In [20]:
data = {
    'sentence' : [],
    'sentiment' : [],
    }
for entry in res:
    sentence = " ".join(entry)
    data['sentence'].append(sentence)

data['sentence']
data['sentiment'] = df['sentiment']

df = pd.DataFrame(data)
df.head()

                           sentence sentiment
0               I responded I going   neutral
1         Sooo SAD I miss San Diego  negative
2                 boss bullying ...  negative
3             interview leave alone  negative
4  Sons put releases already bought  negative

In [21]:
df

                                                sentence sentiment
0                                    I responded I going   neutral
1                              Sooo SAD I miss San Diego  negative
2                                      boss bullying ...  negative
3                                  interview leave alone  negative
4                       Sons put releases already bought  negative
...                                                  ...       ...
27476  wish could come see u Denver husband lost job ...  negative
27477  I wondered rake to. The client made clear .NET...  negative
27478  Yay good you. Enjoy break probably need hectic...  positive
27479                                          But worth  positive
27480       All flirting going The ATG smiles. Yay. hugs   neutral

[27480 rows x 2 columns]

In [22]:
import re
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

nltk.download("punkt")
nltk.download("stopwords")

stop_words = set(stopwords.words("english"))

def preprocess(text):
    text = re.sub(r"[^a-zA-Z0-9\s]", "", text)
    tokens = word_tokenize(text)
    tokens = [w.lower() for w in tokens if w.lower() not in stop_words]
    return " ".join(tokens)

C:\Users\Welcome\AppData\Roaming\Python\Python312\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Welcome\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Welcome\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [26]:
tokenizer = Tokenizer(num_words=5000, oov_token="<OOV>")

tokenizer.fit_on_texts(
    df["sentence"].astype(str).apply(preprocess)
)

sequences = tokenizer.texts_to_sequences(
    df["sentence"].astype(str).apply(preprocess)
)

X = pad_sequences(sequences, maxlen=20, padding="post")

In [27]:
print(X.shape)
print(X[:2])

(27480, 20)
[[   1   12    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0]
 [ 295   49   36 1356 2119    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0]]

In [30]:
X[:1]

array([[ 1, 12,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0]], dtype=int32)